apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  config.yaml: |
    DEBUG: true
    server:
      port: {{ .Values.service.port }}
    target:
      url: {{ .Values.target.url }}